package espacios;

import interfaces.iView;
import javax.swing.JOptionPane;

/**
 *
 * @author Dylan
 */
public class FrmEspacios extends javax.swing.JFrame implements iView<Espacio>{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEspacios.class.getName());

    private EspacioController controller;
    
    /**
     * Creates new form FrmEspacios
     */
    public FrmEspacios() {
        initComponents();
        controller = new EspacioController(this);
        
        cmbTipo.addItem(TipoEspacio.PEQUENO);
        cmbTipo.addItem(TipoEspacio.MEDIANO);
        cmbTipo.addItem(TipoEspacio.GRANDE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEspacios = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblEspBusc = new javax.swing.JLabel();
        lblNumID = new javax.swing.JLabel();
        lblNumID2 = new javax.swing.JLabel();
        lblNumID3 = new javax.swing.JLabel();
        lblNumID4 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        txtTamano = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBuscar.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        lblBuscar.setText("ID/Numero:");

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jLabel2.setText(" Sistema de gestión de espacios");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblEspBusc.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        lblEspBusc.setText("Información del espacio:");

        lblNumID.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        lblNumID.setText("Tamaño Espacio:");

        lblNumID2.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        lblNumID2.setText("Tipo Espacio:");

        lblNumID3.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        lblNumID3.setText("Precio Mensual:");

        lblNumID4.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        lblNumID4.setText("Estado Actual:");

        txtEstado.setEditable(false);
        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });

        txtTamano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamanoActionPerformed(evt);
            }
        });

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        cmbTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEspaciosLayout = new javax.swing.GroupLayout(pnlEspacios);
        pnlEspacios.setLayout(pnlEspaciosLayout);
        pnlEspaciosLayout.setHorizontalGroup(
            pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEspaciosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(pnlEspaciosLayout.createSequentialGroup()
                        .addGroup(pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBuscar)
                            .addComponent(btnLimpiar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(txtBuscar))
                        .addGroup(pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEspaciosLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnBuscar))
                            .addGroup(pnlEspaciosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar))))
                    .addGroup(pnlEspaciosLayout.createSequentialGroup()
                        .addComponent(lblNumID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTamano))
                    .addGroup(pnlEspaciosLayout.createSequentialGroup()
                        .addGroup(pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumID3)
                            .addComponent(lblNumID4))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(txtPrecio)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEspaciosLayout.createSequentialGroup()
                        .addGroup(pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumID2)
                            .addComponent(btnGuardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEspBusc, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnlEspaciosLayout.setVerticalGroup(
            pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEspaciosLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(lblEspBusc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumID2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumID4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumID3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEspacios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEspacios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        String numero = txtBuscar.getText();
        String tamanoText = txtTamano.getText();
        String precioText = txtPrecio.getText();
        TipoEspacio tipo = (TipoEspacio) cmbTipo.getSelectedItem();
        
       if (numero.equals("") || tamanoText.equals("") || precioText.equals("")){
           showError("Digite la informacion de todos los datos");
           return;
        }
       
       try {
            double tamano = Double.parseDouble(tamanoText);
            double precio = Double.parseDouble(precioText);
            Espacio espacio = new Espacio(numero, precio, tamano, tipo);
            controller.agregarEspacio(espacio);
       
        }catch (NumberFormatException e) {
            showError("El tamaño y el precio deben ser valores validos");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        String eliminarNum = txtBuscar.getText();
        
        if (eliminarNum.equals("")){
            showError("Ingrese el ID o numero de espacio a eliminar");
            return;
        }
        
        controller.eliminarEspacio(eliminarNum);
        clear();               
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String numero = txtBuscar.getText();
        
        if (numero.equals("")){
            showError("Digite un ID o  numero de espacio a buscar");
            return;
        }
        
        Espacio espacioEncontrado = controller.buscarEspacio(numero);
        
        if (espacioEncontrado != null) showData(espacioEncontrado);
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        clear();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        String actualizarNum = txtBuscar.getText();
        TipoEspacio tipo = (TipoEspacio) cmbTipo.getSelectedItem();
        
        if(actualizarNum.equals("")){
            showError("Ingrese el ID o numero de espacio a actualizar");
            return;
        }
        
        try{
            double tamano = Double.parseDouble(txtTamano.getText());
            double precio = Double.parseDouble(txtPrecio.getText());
            controller.actualizarEspacio(actualizarNum, precio, tamano, tipo);
        }catch (NumberFormatException e) {
            showError("El tamaño y el precio no son valores validos");
        }           
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtTamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamanoActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed

        TipoEspacio tipoSelecc = (TipoEspacio) cmbTipo.getSelectedItem();
        
        if (tipoSelecc != null){
            double precioBase = Espacio.precioTipo(tipoSelecc);
            txtPrecio.setText(String.valueOf(precioBase));
        }
    }//GEN-LAST:event_cmbTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmEspacios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<TipoEspacio> cmbTipo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblEspBusc;
    private javax.swing.JLabel lblNumID;
    private javax.swing.JLabel lblNumID2;
    private javax.swing.JLabel lblNumID3;
    private javax.swing.JLabel lblNumID4;
    private javax.swing.JPanel pnlEspacios;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTamano;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clear() {
        txtBuscar.setText("");
        txtTamano.setText("");
        txtPrecio.setText("");
        txtEstado.setText("");
        cmbTipo.setSelectedIndex(0);
    }

    @Override
    public void showData(Espacio data) {
        if (data == null) return;
        txtBuscar.setText(data.getNumero());
        cmbTipo.setSelectedItem(data.getTipo());
        txtTamano.setText(String.valueOf(data.getTamano()));
        txtPrecio.setText(String.valueOf(data.getPrecioMes()));
        txtEstado.setText(data.getEstado().getEstado());
    }

    @Override
    public void showError(String error) {
        JOptionPane.showMessageDialog(this, error, "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Mostrar mensaje", JOptionPane.INFORMATION_MESSAGE);
    }
}
